name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install Chrome
    - name: Setup Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Display Chrome Version
      run: |
        echo "CHROME VERSION:"
        google-chrome-stable --version

    - name: Install ChromeDriver
      run: |
        CHROME_MAJOR_VERSION=$(google-chrome-stable --version | awk '{ print $3 }' | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}")
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Display ChromeDriver Version
      run: |
        echo "CHROMEDRIVER VERSION:"
        chromedriver --version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: List directory contents  # Debugging step
      run: ls -R

    - name: Run Tests
      run: |
        robot --variable BROWSER:headlesschrome -d Results RobotFrameworkTests/Tests/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Results/
