name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: List Directory Structure
      run: ls -R .
    
    - name: Run tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: 'RobotFrameworkTests'
        robot_reports_dir: 'reports'
    - name: Store test report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports

  report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download test report
      uses: actions/download-artifact@v1
      with:
        name: reports
