name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    - name: Debug Chrome Version
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{ print $3 }')
        echo "Chrome Version: $CHROME_VERSION"

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{ print $3 }' | sed 's/\([0-9]*\.[0-9]*\).*/\1/')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Driver Version: $DRIVER_VERSION"
        wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: List directory contents  # Debugging step
      run: ls -R

    - name: Run Tests
      run: |
        robot --variable BROWSER:headlesschrome -d Results RobotFrameworkTests/Tests/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Results/
