name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: List Directory Structure
      run: ls -R .

    - uses: nanasess/setup-chromedriver@v2
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        
    - name: Check Chrome and ChromeDriver version
      run: |
        google-chrome-stable --version
        chromedriver --version

    - name: Check where chromedriver is located
      run: which chromedriver
      
    - name: Check where Chrome is located
      run: which google-chrome-stable

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r ./SeleniumTests/requirements.txt

    - name: Run the PytTest script
      run: pytest --html=report.html

  report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
