name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: List Directory Structure
      run: ls -R .

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r ./SeleniumTests/requirements.txt
      
    - name: Install specific Chrome version
      run: |
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
        sudo dpkg -i google-chrome-stable_114.0.5735.90-1_amd64.deb
        sudo apt-get install -f

    - name: Install corresponding ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin/


    - name: Run the PytTest script
      run: pytest -r ./SeleniumTests

  report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
