name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: List Directory Structure
      run: ls -R .
      
    - name: Run Pytest
      uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r requirements.txt && python ./SeleniumTests/run.py

    - name: Upload Pytest Reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-reports
        path: pytest-reports

  report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
