name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: List Directory Structure
      run: ls -R .
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install software
      run: sudo apt-get install -y chromium-browser
    - name: Install the necessary packages
      run: pip install requests webdriver-manager selenium pytest
    - name: Run the PytTest script
      run: pytest -r ./SeleniumTests

  report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
