name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t mytestimage .

    - name: Run Pytest in Docker container
      run: docker run mytestimage python ./SeleniumTests/run.py

  report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
