name: Run Selenium (Pytest) Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install selenium pytest

    - name: List Directory Structure
      run: ls -R .

    - name: Run Pytest
      run: python ./SeleniumTests/run.py
    
  report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Pytest Reports
      uses: actions/download-artifact@v2
      with:
        name: pytest-reports
